- hosts: hadoop_workers
  user: root
  vars:
    hadoop_dir: /my-hadoop-install
  tasks:
    # - debug: var=ansible_default_ipv4.address
    - name: "create ssh directory"
      file: path=~/.ssh state=directory
    - name: Include vars of secrets.yaml into the 'secrets' variable.
      include_vars: 
        file: ./secrets.yml
        name: secrets
    # - debug: var=secrets.vars.rsa_pubkey_master
    - name: "add master public key to authorized keys file"
      lineinfile: 
        path: ~/.ssh/authorized_keys
        line: "{{ secrets.vars.rsa_pubkey_master }}"
        create: yes
    - name: copy hdfs-site.xml file from source to each worker node
      copy: 
        src: "./_hdfs-site-worker.xml"
        dest: "{{ hadoop_dir }}/hadoop-3.0.3/etc/hadoop/hdfs-site.xml"